### ISSUE TITLE
ISSUE Focus using the F button and focus centre.

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#10]
I am having a few issue with this, it seems a bit counter intuitive to what the focus point is.
When focusing with F, some of the buttons are getting cut outside the viewer,  it seems counter productive, since it requires the user to zoom out and recentre with the mouse.

The way i would see this working is like this : 
With No buttons selected inside the viewer, pressing F would focus the entire buttons layout and zoom to fit in the scaled UI view.(you would see everything)
With Multiple buttons selected, pressing F would centre focus on the middle point between the selected buttons and zoom the UI to fit the view of such buttons.(eg 3 buttons are selected, they are fully visible in the UI view)
With One button selected, pressing F would focus and zoom the UI view to the selection.

**Comment by luckylyk** [comment]
You can configure the focus center by picker using that button:
![image](https://user-images.githubusercontent.com/25019043/149657836-bc3ed70f-065b-4b61-91ee-5b9592a7dd6f.png)

An auto fit-content is wip when the user is adding a button out of the picker.

Design a Focus fitting to content is a lot of work, I'll add it to our TODO but do not wait it for too soon.

**Comment by alfsici** [comment]
Thank you for the quick update, i was wondering if a "focus on the current mouse point on the UI" would be a quicker more viable solution to implement.
That way perhaps, when you select something and press F, the center of focus moves to the mouse position on the canvas, and when nothing is selected, the view gets simply zoomed out to show the full background of the layout.
Either ways, thank you again for the tool, it is very solid work , i know how tricky it is to implement these type of behaviors in Qt.

**Comment by KnIVan** [comment]
Hello, when embedding a picker window in maya, it intercepts hotkeys such as:

ctrl+z
ctrl+s
F

**Comment by luckylyk** [comment]
This is another topic, i created another issue

**Comment by ndeebook** [comment]
Hello,
We just added the feature in the latest commit. It will be there in the next release !
