### ISSUE TITLE
Hovered background color for a button doesn't work when the action is a script

### ISSUE THREAD

**Issue by sebasti1a** [DreamWall-Animation/dwpicker#101]
Hi, we use dwpicker 0.11.2, when i add script python on my button wihout "targets" , hovered background color for a button doesn't work. Is this expected behavior or a bug? Thanks.

![image](https://github.com/user-attachments/assets/821857db-13f4-4da3-9b56-50cf6f38d859)

**Comment by luckylyk** [comment]
bug indeed :)

**Comment by luckylyk** [comment]
This is fixed in the latest commit !
Will come officially in the next release 0.11.3
