### ISSUE TITLE
Update button target by command

### ISSUE THREAD

**Issue by marco-anm** [DreamWall-Animation/dwpicker#103]
Hi! Was looking for a self-update button but I can't found a way. I want to dissable edit mode on the picker but keeping a couple of buttons for props that can be updated by pressing ctrl+click. Is there an easy way to call "update_button" from command?

Thanks for your amazing work!

**Comment by luckylyk** [comment]
You mean: update Target from selection ? I'm afraid there is nothing like this available nor something easy to implement for the case you describe. Sorry

**Comment by luckylyk** [comment]
Without any precisions, I'm closing the ticket
Feel free to reopen if you have more information to provide
