### ISSUE TITLE
error no attribute show

### ISSUE THREAD

**Issue by joda1999** [DreamWall-Animation/dwpicker#105]
i has this error that says this.
 Error: AttributeError: file <maya console> line 2: module 'dwpicker' has no attribute 'show'

**Comment by luckylyk** [comment]
Hi,
are you sure you are using the latest picker version ? Combined with which maya version ? Some older version were broken with Maya's older than 22. But the latest one should be could.

**Comment by luckylyk** [comment]
Seems that I need more information to help.

Could you ensure you have this checked in the script editor
![image](https://github.com/user-attachments/assets/a70dfc60-f27b-47d7-b51a-f6a3aa2dd665)

Launch a maya, run the picker startup command:
```import dwpicker
dwpicker.show()```

At that step, I need you provide me the entire output the script editor. And the entire output from the Maya's Output window that you can find here:
![image](https://github.com/user-attachments/assets/ad7884a8-f522-45fc-93f3-4d3b18db8ee8)

**Comment by luckylyk** [comment]
Without any news I'm closing the ticket.
Feel free to reopen if you have more details to provide.
