### ISSUE TITLE
Invalid flag 'majorVersion'

### ISSUE THREAD

**Issue by iph0ne20** [DreamWall-Animation/dwpicker#106]
Hello!
I'm trying to install the script but this error keeps popping-up: # Error: TypeError: file C:/Users/[user]/Documents/maya/scripts\dwpicker\__init__.py line 7: Invalid flag 'majorVersion'
Am I doing something wrong?

**Comment by luckylyk** [comment]
Hi !
Can you specify which maya's version you are using ?

**Comment by iph0ne20** [comment]
I'm using the 2019 version!

**Comment by iph0ne20** [comment]
Works perfectly now! Thanks a lot and sorry for the trouble!

**Comment by luckylyk** [comment]
you are welcome
