### ISSUE TITLE
Background doesn't show up

### ISSUE THREAD

**Issue by CeliaDst** [DreamWall-Animation/dwpicker#109]
Hi, hope you're ok!

I have a little issue with the picker, I can't add a background.

It's a png, I tried to add it with those two methods:
- Edit, Add background item.
- Edit, Advanced editing, Uncheck Lock background items, v Image, add Path.

Thanks in advance for your response!

**Comment by luckylyk** [comment]
Hi Celia,
Could you provide more specific infos ?
Picker version, maya version, OS and do you have any error message in the Maya's script editor (ensuring the Stack trace is activated)

![image](https://github.com/user-attachments/assets/15b2320c-d591-4a22-b7c5-7b10bf15bdba)

**Comment by luckylyk** [comment]
Without any news, I'm closing the ticket

Feel free to reopen if you provide more information
