### ISSUE TITLE
Mirroring Widget

### ISSUE THREAD

**Issue by Herizoran** [DreamWall-Animation/dwpicker#11]
Hello guys,
This is just a suggestion for enhancement.
It would be better if there was a dialog Search and Replace prompt after clicking the mirror button.
This is an example from the mGear Anim Picker. 

![DUPLICATE AND MIRROR](https://user-images.githubusercontent.com/97302382/150289251-b55a567d-f070-44c7-9e84-aed743bac0d7.gif)

**Comment by luckylyk** [comment]
The search and replace is there:
![image](https://user-images.githubusercontent.com/25019043/150310997-86c86d51-55f1-4a0d-976e-013eb06f3947.png)
But yeah, you had to manually trigger it after a mirroring.

Only for you I added and option to trigger it automatically after mirroring :)
![image](https://user-images.githubusercontent.com/25019043/150310889-512dde81-ebdc-4378-9a5f-609277eca60e.png)

**Comment by Herizoran** [comment]
Yeah, my bad! 😆
Thank you!
