### ISSUE TITLE
Loading a blank picker window but not the json or the image

### ISSUE THREAD

**Issue by fruitskin** [DreamWall-Animation/dwpicker#111]
Great piece of software - thanks. We have encountered an odd thing happening...

Since upgrading our machine to Windows 11 (from 10) there seems to be an issue where the picker window spawns but the actual picker does not - neither does the image.

<img width="1124" alt="03" src="https://github.com/user-attachments/assets/0603e1b0-64ad-4ecf-ac04-2227aec8a11c" />

It works fine on the previous machine.

When we try to manually open the json file we get the following error. This image shows us opening the json.

<img width="2560" alt="04" src="https://github.com/user-attachments/assets/e94355ac-32f4-4441-a823-5a82916c08da" />

Results in the blank picker and gives this error.

`Traceback (most recent call last):
File "C:\Users/israel/Documents/maya/scripts\dwpicker\main.py", line 523, in call_open
self.add_picker_from_file(filename)
File "C:\Users/israel/Documents/maya/scripts\dwpicker\main.py", line 466, in add_picker_from_file
ensure_images_path_exists([data])
File "C:\Users/israel/Documents/maya/scripts\dwpicker\references.py", line 22, in ensure_images_path_exists
dialog = MissingImages(missing_images)
File "C:\Users/israel/Documents/maya/scripts\dwpicker\dialog.py", line 241, in init
self.browse = QtWidgets.QPushButton(icon('mini-open.png'))
TypeError: # 'PySide2.QtWidgets.QPushButton' called with wrong argument types:
PySide2.QtWidgets.QPushButton(QIcon)
Supported signatures:
PySide2.QtWidgets.QPushButton(PySide2.QtGui.QIcon, str, typing.Optional[PySide2.QtWidgets.QWidget] = None)
PySide2.QtWidgets.QPushButton(typing.Optional[PySide2.QtWidgets.QWidget] = None)
PySide2.QtWidgets.QPushButton(str, typing.Optional[PySide2.QtWidgets.QWidget] = None)`

Were using Maya 2024.2 on both machines and in both cases we are running the picker from a sync server - (works on the Windows 10 machine)

This is how it should look.

<img width="2560" alt="02" src="https://github.com/user-attachments/assets/e22d0a98-d19b-4f70-a848-b9b323adcc32" />

We have tried re-installing maya and dw picker. 

If you have any guidance we would be very grateful indeed.

Thanks
Joe

**Comment by luckylyk** [comment]
Seems you maya 2024 is not able to find the BG image and the "Missing File" dialog bog is bugged in latest version. Just committed an update (not released but, you can try it out getting the latest code published here: 
![image](https://github.com/user-attachments/assets/503d7f9d-9e14-4622-a62e-e7bd86e93a62)
)

**Comment by fruitskin** [comment]
Thank you so much - its working now.
