### ISSUE TITLE
does it have ability to collect multiple controls in one button?

### ISSUE THREAD

**Issue by ann40** [DreamWall-Animation/dwpicker#17]
Hi, one thing in animschool picker is that we were able to select multiple controls and create a button for that, which is very handy and helpful, I didn't see that option in the picker, wonder if i missed it somewhere. It's not a bug though, but I don't know where else I should wrote this.

**Comment by ann40** [comment]
sorry I found it has, don't know how to close this.

**Comment by luckylyk** [comment]
Auto resolved ticket ! The best ones :)
