### ISSUE TITLE
copy and pasting

### ISSUE THREAD

**Issue by Sidchou** [DreamWall-Animation/dwpicker#18]
Great tools, thanks for developing this, i have a few issue working with it tho

1. copy and pasting hex code for color does not apply
2. copy and pasting element reset some attribute, ie show boarder
3. would be great if there's a method for loading files so i can create a custom shelf that will load everything up

appreciate the work

**Comment by luckylyk** [comment]
Hi Sidchou,
1. I will take a look.
2. Can be a bit more precise and explain how to reproduce this ?
3. This is already possible with latest commit (not documented yet by the way)
```dwpicker.show(editable=True, pickers=["file_name1", "file_name2" ...], ignore_scene_pickers=True):```
editable = allow animator to edit the picker (only affect the scene)
pickers = path to json files
ignore_scene_pickers = doesn't load the picker self contained in the scene and flush the tabs.

**Comment by Sidchou** [comment]
to #2 i was using the advance editor, as is #1, i realized i might have changed the drop down while scrolling accidentally. 
3. i did read the repo and try to use it, but i was passing the one path as string instead of array, so it parse the string as array, changing that does work.
