### ISSUE TITLE
'unicode' is not defined

### ISSUE THREAD

**Issue by SupZeta** [DreamWall-Animation/dwpicker#2]
Hi,

Firts of all congratz for this amazing picker and for ending the AnimSchool monopoly. 

Me and other animators are all having the same problem loading the picker.

# Error: NameError: file C:/Users/User/Documents/maya/scripts\dwpicker\optionvar.py line 59: name 'unicode' is not defined # 

Im using Maya 2022, Win10.
Any solution to this?

Cheers.

**Comment by luckylyk** [comment]
Hi, Maya2022 is using python 3 which cause that issue.
I don't tested yet the picker in that environment (it will be done asap)

Then I can't promise that you will not encounter other issues until it will released safe for 2022. At that time, I just pushed a small fix for that particulary bug. It is not included in a release but you can download the code directly. ::crossed_fingers::

I'll advance the python3 milestone for next friday (But i think i should be done before)

Thanks for the support and the report.

**Comment by SupZeta** [comment]
Same error, different line.

# Error: NameError: file C:/Users/Zaka/Documents/maya/scripts\dwpicker\optionvar.py line 71: name 'unicode' is not defined # 

I guess we have to wait for a 2022 release. 

Thanks.

**Comment by luckylyk** [comment]
Ok :s 
Sorry if I had a maya 22 on my personnal machine, I would fix that directly, but it will have to wait i'm back to the studio.
Don't worry, it will be really soon :)

**Comment by luckylyk** [comment]
Hoo damn, I'm so clumsy .. Looking at the fix, i made it but left behind the failing lines. Actually, this error should be gone now.

**Comment by SupZeta** [comment]
Working perfectly now!
Thank you!!

**Comment by luckylyk** [comment]
Maya 2022 officially supported :) !
