### ISSUE TITLE
Maya Navigation

### ISSUE THREAD

**Issue by johnturello** [DreamWall-Animation/dwpicker#22]
Is it possible to add right click zoom as the default preference so that it is consistent with maya? Also it currently only zooms when the cursor moves up and down, would it be possible to add left and right as well like maya/animschool picker?

**Comment by luckylyk** [comment]
Hi John,
The zoom button is optionnal and can be changed
![image](https://user-images.githubusercontent.com/25019043/155008755-f21c3b98-69ae-4298-908e-4dff53d5e12e.png)

The left and right zoom is added to latest commit :)
