### ISSUE TITLE
Hello, when embedding a picker window in maya, it intercepts hotkeys such as:

### ISSUE THREAD

**Issue by luckylyk** [DreamWall-Animation/dwpicker#23]
Hello, when embedding a picker window in maya, it intercepts hotkeys such as:

ctrl+z
ctrl+s
F

And if possible, please make the window embedding into the interface as in the animshool picker (double click on the top)

Thanks for the great picker.

_Originally posted by @KnIVan in https://github.com/DreamWall-Animation/dwpicker/issues/10#issuecomment-1063928907_

**Comment by luckylyk** [comment]
mmmh I can reproduce indeed :/
Such no idea how to fix this currently. I'm investigating.

**Comment by luckylyk** [comment]
This is fixed by last commit !
Thanks for this report, it brings a valuable improvement.

**Comment by KnIVan** [comment]
Thank you very much for the cool picker.
