### ISSUE TITLE
Close window editor

### ISSUE THREAD

**Issue by KnIVan** [DreamWall-Animation/dwpicker#24]
If I grab the corner of the Picker editor window and want to resize it, the window automatically collapses. This happens if I created the picker myself in DW. If I open a picker that I converted from animschool everything works fine.

https://youtu.be/YA-La32zl3A

UPD: I found the reason. It limits the size of the window to the size of the background. If possible, correct it so that it is not limited to the backround and you can resize it as convenient. Thanks.

**Comment by luckylyk** [comment]
Nice guess. I will take time to put the editor area in a scroll widget when size is too big. I'll fix that monday.

**Comment by KnIVan** [comment]
> Хорошая догадка. Я потрачу время, чтобы поместить область редактора в виджет прокрутки, когда размер слишком велик. Я исправлю это в понедельник.

Дякую!

**Comment by luckylyk** [comment]
This is fixed by commit: https://github.com/DreamWall-Animation/dwpicker/commit/95057cd1ef709600d6c5ea643934e342b0f7842f

The shape editor area is included in a scroll area (never too late to do this ^^')

слава україні

**Comment by KnIVan** [comment]
Thank you, you are the best!
