### ISSUE TITLE
Cant save picker

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#25]
# Traceback (most recent call last):
#   File "C:/Users/fax/Documents/maya/2019/scripts\dwpicker\main.py", line 350, in call_save_as
#     self.update_namespaces()
# TypeError: 'int' object is not callable

i can not save picker

**Comment by luckylyk** [comment]
Hi, i cannot reproduce that issue.
Could you give me more precision about how it is happening ? Or provide a maya scene containing the picker ?

**Comment by Chuanzhen187** [comment]
> Hi, i cannot reproduce that issue. Could you give me more precision about how it is happening ? Or provide a maya scene containing the picker ?

Hi,Thanks for you reply! i restart computer ,it work.I'm not sure why this happened.

**Comment by luckylyk** [comment]
Probably a conflit with another script i guess
