### ISSUE TITLE
Wacom pen Scale View issue

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#26]
Hi,using wacom pen to zoom the view is not friendly and changes too fast. Similarly,  “ALT + pressing the  withmiddle mouse button” is as unfriendly as wacom pen. It changes too fast. The use of mouse wheel sliding zoom experience is very friendly. Can this be optimized? Quite a few animators use wacom pen

**Comment by luckylyk** [comment]
Zoom sensitivity is configurable in Edit->Préférences.
Tell me if you can find a satisfying setting or if it is still too sensitive using the max setting.

**Comment by Chuanzhen187** [comment]
> Zoom sensitivity is configurable in Edit->Préférences. Tell me if you can find a satisfying setting or if it is still too sensitive using the max setting.

Thanks for your reply! 
This setting is really easy to use, but if the sensitivity is set to the minimum value, it is still not enough. It should be better if you can set a smaller value！

**Comment by luckylyk** [comment]
I dont have savon to test what would the best setting. To avoid endless back ans forth, could you edit that value ?

![Screenshot_20220312-131159](https://user-images.githubusercontent.com/25019043/158017573-f66a44fb-09d5-4e8c-aa60-a5cf46cb2a04.png)

Higher the value will be set, lower the minimum sensivity will be. 
If  you find a good one, I will report it to the tool.

**Comment by Chuanzhen187** [comment]
> I dont have savon to test what would the best setting. To avoid endless back ans forth, could you edit that value ?

ok

**Comment by Chuanzhen187** [comment]
I didn't find a good value. 500 seems to be a little better, but the zoom view is still not smooth

**Comment by luckylyk** [comment]
Ok I found a wacom to test,
The zoom algorithm is currently very straight forward.
I will try to improve that system ASAP

**Comment by luckylyk** [comment]
Ok with latest commit, after an awfull head-hack, I think I found a way much better zoom algorithme.
Can you try it and tell me if it looks better to you ?

**Comment by Chuanzhen187** [comment]
> Ok with latest commit, after an awfull head-hack, I think I found a way much better zoom algorithme. Can you try it and tell me if it looks better to you ?

OK, I'll try the new version

**Comment by Chuanzhen187** [comment]
The new version has smooth zoom and good experience. Great job！

**Comment by luckylyk** [comment]
:)
