### ISSUE TITLE
not fully working on maya 2020.2?

### ISSUE THREAD

**Issue by miksand** [DreamWall-Animation/dwpicker#27]
Hi, 
I have tried this on Maya 2019 and it works nice.
The next day I tried in Maya 2020.2, in the Advanced Editing I can not drag and scale the buttons manually (no little white dots around the button appear), can only edit them by the numbers in boxes on the right.

**Comment by luckylyk** [comment]
Hi Miksand
Can you confirm this is still the case with the latest picker commit ?
It seems that issue appeared last week for a small short time but fixed now.
See issue #19

**Comment by miksand** [comment]
Hi, thanks for the reply.
I've just downloaded the newest version just now.
I'm afraid it's still the case. I think it's different with case #19 , because advanced edit window appears here, it's just I can not drag and scale things manually inside it. I attach a pic to make it clearer.

![Screenshot 2022-03-15 182412](https://user-images.githubusercontent.com/101617488/158370269-c9cb5119-a5d3-4b02-ac75-3cb4988c93e5.png)


Here's what i got from error warning:

# Traceback (most recent call last):
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 79, in mousePressEvent
#     self.update_selection()
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 173, in update_selection
#     rect = get_combined_rects([shape.rect for shape in self.selection])
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\geometry.py", line 451, in get_combined_rects
#     if rect is Nones:
# NameError: global name 'rect' is not defined
# Traceback (most recent call last):
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 79, in mousePressEvent
#     self.update_selection()
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 173, in update_selection
#     rect = get_combined_rects([shape.rect for shape in self.selection])
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\geometry.py", line 451, in get_combined_rects
#     if rect is Nones:
# NameError: global name 'rect' is not defined
# Traceback (most recent call last):
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 79, in mousePressEvent
#     self.update_selection()
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 173, in update_selection
#     rect = get_combined_rects([shape.rect for shape in self.selection])
#   File "C:/Users/mikail/Documents/maya/2020/scripts\dwpicker\geometry.py", line 451, in get_combined_rects
#     if rect is Nones:
# NameError: global name 'rect' is not defined

**Comment by luckylyk** [comment]
I confirm that is the exact same thing that issue #19.
I'm more than sure that the executed version is not the last commit. If you just installed the latest version, I assume you have an old one somewhere in the script folders or set in you environment. Or replacing the folder didn't erased the files properly.
I invite you to check if the path displayed in the error correspond to the path you installed the latest version. Or open the 'geometry.py' file and verify if the code at line 451 is: `if rect is Nones`, because it is supposed to be: `if not rects`.

**Comment by luckylyk** [comment]
I close the ticket as I believe there is no issue.
Do not hesitate to re-open or create another one if you have new concerns.

**Comment by miksand** [comment]
Yes, it works after replacing with the supposed codes! Thank you so much.

![image](https://user-images.githubusercontent.com/101617488/158569965-8cb8f423-f755-444b-8bed-e4c00ab61320.png)

**Comment by luckylyk** [comment]
You are welcome :)
