### ISSUE TITLE
ALT-middle to zoom in zoom out the window is too sensitive

### ISSUE THREAD

**Issue by ann40** [DreamWall-Animation/dwpicker#28]
Hi, I am uisng pen most of time for working, and I found that the alt-middle mouse button to zoom in zoom out is a bit too sensitive in the window, which is making the zoom in quite hard to use. Is there way to solve it?

**Comment by ann40** [comment]
oh I found it in the preference, never mind!

**Comment by luckylyk** [comment]
I think the zoom is fixed now.
