### ISSUE TITLE
Is there way to zoom in and out in advanced editing?

### ISSUE THREAD

**Issue by ann40** [DreamWall-Animation/dwpicker#29]
When I am editing the finger picker, since the finger pickers I created are very small so I wish to zoom in to move them around at the right place, but I didn't find a way to zoom in in advanced editing though.

**Comment by luckylyk** [comment]
It is not planned for a close futur due to the amount of work and the widget complexification it does represent.
But it is not a definitive 'no' either. That is a recurring request.
Sorry
