### ISSUE TITLE
Tab updates

### ISSUE THREAD

**Issue by slumbertwo** [DreamWall-Animation/dwpicker#3]
Wow --this is great! I've been frustrated by the AnimSchoolPicker, wishing I could tweak things for our pipeline. I love your tool (and it's transparency).

There are two minor bugs I still find in the latest download:

1. If you reorder your tabs, close the picker, and reopen the tabs revert to alphabetical.
2. If you delete a tab, and close the picker, it will reappear when reopened.

In both cases it seems like the state of the picker isn't being saved after a change (hopefully a minor fix).

Thanks again!
 Matthew

**Comment by luckylyk** [comment]
Hey :) I'm glad that you enjoy the picker and it's is usefull for you. 
Indeed it is very open and as simple a possible to script for pipeline purpose :)

Fix done ! (not included in proper release yet, but reachable downloading source code)

Thanks for your feedbacks and contributing to make it better !

**Comment by slumbertwo** [comment]
That was fast! Thanks v. much :)

**Comment by luckylyk** [comment]
You are welcome :)
