### ISSUE TITLE
How do I check how many background images is in my file?

### ISSUE THREAD

**Issue by ann40** [DreamWall-Animation/dwpicker#30]
I wanted to replace the previous background, so I tried several ways, one is by clicking Edit- add background item, but I found that is actually adding other images below the current background, and right now I've found correct way to replace it, but I don't know how to delete the images below.

**Comment by luckylyk** [comment]
Indeed 'add background' is a bit odd. We added it to mock the AnimSchool function and help transition for animators doing the migration.
Actually the DW Picker is working differently, so there is no way to him to discriminate which item is the background as far it is the same object than any other button. There is no limit in the images you can put.
To edit those 'non interactive' items, you have to uncheck this button in the advanced editor toolbar:
![image](https://user-images.githubusercontent.com/25019043/158469857-b591300b-9ec4-4537-8aff-35b2af7e5d77.png)
They will become selectable, resizable and editable.

**Comment by ann40** [comment]
ok thanks
