### ISSUE TITLE
preference window can not open

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#31]
When I start Maya and open the dwpicker window for the first time, I can open the preference window, but when I fix dwpicker in Maya's interface, clicking again to open the preference window has no response.
![test](https://user-images.githubusercontent.com/46336185/158521328-ed159136-50bf-4936-a033-158fcdf9147f.gif)

**Comment by luckylyk** [comment]
That was an issue in maya parenting managment
This should be fixed by last commit
