### ISSUE TITLE
new_version  0.4.0 not show picker

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#33]
maya file work with dwpicker 0.2.0  works fine. when i use dwpicker 0.4.0, open maya file,the picker not show. 
script Editor show:
```# Traceback (most recent call last):
#   File "C:/Users/cz/Documents/maya/scripts\dwpicker\picker.py", line 230, in mouseMoveEvent
#     self.viewportmapper.to_units_coords(event.pos()),
#   File "C:/Users/cz/Documents/maya/scripts\dwpicker\geometry.py", line 44, in to_units_coords
#     self.to_units(pixels_point.x() + self.origin.x()),
#   File "C:/Users/cz/Documents/maya/scripts\dwpicker\geometry.py", line 35, in to_units
#     return pixels / self.zoom
# ZeroDivisionError: float division by zero
```

version 0.2.0 work fine
![xx](https://user-images.githubusercontent.com/46336185/159859565-daa4823b-b434-4089-bc76-23bbc15d1b24.png)
 version 0.4.0 reopen maya file ,picker not show
![xxx](https://user-images.githubusercontent.com/46336185/159859872-48add842-ba36-4b9a-a8ee-6ee89c8ec71a.png)

**Comment by luckylyk** [comment]
Indeed, we made a conversion mistake only with python2
Release 0.4.1 got the fix.

Thanks for the report.
