### ISSUE TITLE
Align and Distribute items function

### ISSUE THREAD

**Issue by kalemas** [DreamWall-Animation/dwpicker#34]
HI, thanks fo so cool project!

May i commit some missed functionality here i case we or any one else to implement this.

It is inconvenient without a function to align selector items in editor mode. Vertical and Horizontal alignment, align by Center and both boundaries - 6 buttons at all.

Vertical and horizontal distribution would be helpfull too.

**Comment by luckylyk** [comment]
Same reply as #35

**Comment by kalemas** [comment]
Sorry for delay (i hoped to test yet). You are awesome!!!
