### ISSUE TITLE
Can not enter the edit mode

### ISSUE THREAD

**Issue by amazing89** [DreamWall-Animation/dwpicker#36]
# Traceback (most recent call last):
#   File "C:/Users/wangyan27/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 163, in paintEvent
#     self.paint(painter)
#   File "C:/Users/wangyan27/Documents/maya/2020/scripts\dwpicker\designer\editarea.py", line 170, in paint
#     shape.draw(painter)
# AttributeError: Shape instance has no attribute 'draw'

when entering the edit mode(Ctrl + E), this error pops out, I'm using Maya 2020. Anyone could help? Thanks a lot.

**Comment by luckylyk** [comment]
My bad, savage refactoring.
This is fixed by latest commit

**Comment by amazing89** [comment]
Awsome~!
