### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by KnIVan** [DreamWall-Animation/dwpicker#37]
Hello, I made myself an icon for a picker shelf. If you like, you can use it in the general pack. ;)

https://drive.google.com/drive/folders/1PSNY-K7aX-yObHj1ZSrEkDSeXjzeGovZ?usp=sharing

**Comment by luckylyk** [comment]
Hey !
Thanks for this ! It is very cute. But i think on our animators already reserved the right to make the 'official icon' :)

good luck.
