### ISSUE TITLE
Picker disappeared inexplicably

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#38]
Sometimes, when the asb file is overloaded or the reference is overloaded, the existing picker disappears. However, this problem cannot be fixed and reproduced, but this problem has been encountered several times
version 0.4.5

**Comment by luckylyk** [comment]
Hi, what do you mean by asb file ?

**Comment by Chuanzhen187** [comment]
a kind of file,When the reference is very large and reloaded, the picker may be lost.

**Comment by luckylyk** [comment]
Hey, could you give a try on the latest version ? I think the latest update fixed that issue.

**Comment by luckylyk** [comment]
Without update from a while and supposing this is fixed by latest commit, I'm closing this ticket.
Do not hesitate to-reopen it if the problem persiste on your side.
