### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by Alehaaaa** [DreamWall-Animation/dwpicker#39]
As this is an ongoing project there are so many updates, and having to check github every now and then is pretty annoying.
I've seen other tools have a very simple Update button which compares the localVersion with the currentVersion. Then downloads, unpacks, replaces and rehashes the Tool.

Is there any way of implementing this onto here? That would be awesome.

**Comment by luckylyk** [comment]
Hi Alehaaa,
This hard because it could fail for too many thing depending on user contexte (OS, VPN, User rights ...)
And for security reasons, i refuse to implement an official button to do this.

By the way, i'll check if i can easily  add a code snipet in the script folder doing this. 
I cant promise anything, not sure it is easy to communicate with Github using python.

Other solution for you, is to locally clone the repository and pull it when you want an update.

**Comment by Alehaaaa** [comment]
I'll take a look at what I can do to updates easier.

You should check out [MKlimenko](https://github.com/MKlimenko)'s [aTools script conversion](https://github.com/MKlimenko/aTools_python3), from python2 to python3.
Whereas the original script downloaded the old python2 **.zip** file, he managed to get it to work hosting his version on GitHub.

Also, Reddit user [WiDOC38](https://www.reddit.com/user/WiDOC38/) also converted the script [TweenMachine to python3](https://www.reddit.com/r/Maya/comments/tqbs1d/update_tweenmachine_for_maya_2022_python_3/); and, even if it wasn't fully implemented, the script had a **function** called `update_check()` which, obviously, checked for a newer version.

Let me know if you are interested in spending some time on this matter!

**Comment by luckylyk** [comment]
After taking a look, it seems convoluted because the each release has his own path. I don't find easy solution (avoiding to change the release setup) to gather that latest url available. I'll skip this one sorry

**Comment by Alehaaaa** [comment]
`latestUrl = "https://github.com/DreamWall-Animation/dwpicker/releases/latest"

latestUrl = urllib.request.urlopen(latestUrl).read()
i = latestUrl.decode("utf-8")
i = i.split("}...")[1]

latestVersion = (i[:16])

cmds.showHelp("https://github.com/DreamWall-Animation/dwpicker/archive/refs/tags/" + latestVersion + ".zip", absolute=True)
`
Let me know if this is usable. Even though I know almost nothing about programming, I've managed to make it work.
Most likely it is a very poor way of going around this but had an idea and wanted to see if it would work.

**Comment by ndeebook** [comment]
Good idea. Using the redirected URL looks reliable:
```from urllib.request import urlopen
latest_url = 'https://github.com/DreamWall-Animation/dwpicker/releases/latest'
version = urlopen(latest).url.split('/')[-1]```

**Comment by luckylyk** [comment]
Go head Oli :)

**Comment by ndeebook** [comment]
Update checker will be released in the afternoon

**Comment by Alehaaaa** [comment]
Thanks! I see that the user still has to download and replace the files manually, in my spare time I'll try to program that process automatically (don't expect much) and let you know!!

**Comment by Alehaaaa** [comment]
This code based on aTool's installation, downloads the latest version and substitutes the old one (a function to save optionvar.py file has to be implemented).

It should run on ok_btn.released

`from maya import cmds, mel
import os, shutil, urllib.error, urllib.parse, shutil, zipfile

def formatPath(path):
    path = path.replace('/', os.sep)
    path = path.replace('\\', os.sep)
    return path

def download(DOWNLOAD_URL, saveFile):
    response = urllib.request.urlopen(DOWNLOAD_URL, timeout=60)

    try: response
    except: pass
    
    if response is None: 
        cmds.warning('Error trying to install.')
        return
    output = urllib.request.urlretrieve(DOWNLOAD_URL, saveFile)
    return output

LATEST_RELEASE_URL = (
    'https://github.com/DreamWall-Animation/dwpicker/releases/latest')

def DWInstall():
    mayaAppDir      = mel.eval('getenv MAYA_APP_DIR')    
    DWPath          = mayaAppDir + os.sep + "scripts"
    DWFolder        = DWPath + os.sep + "dwpicker" + os.sep
    tmpZipFile      = "%s%stmp.zip"%(DWPath, os.sep)
    latest_version = urllib.request.urlopen(LATEST_RELEASE_URL).url.split('/')[-1]
    DOWNLOAD_URL = 'https://github.com/DreamWall-Animation/dwpicker/archive/refs/tags/{0}.zip'.format(latest_version)
        
    if os.path.isfile(tmpZipFile):     os.remove(tmpZipFile)   
    if os.path.isdir(DWFolder): shutil.rmtree(DWFolder)      
    
    output = download(DOWNLOAD_URL.format(), tmpZipFile)    
    
    zfobj = zipfile.ZipFile(tmpZipFile)
    for name in zfobj.namelist():
        uncompressed = zfobj.read(name)
    
        filename  = formatPath('%s%s%s'%(DWPath, os.sep, name))
        d         = os.path.dirname(filename)
        
        if not os.path.exists(d): os.makedirs(d)
        if filename.endswith(os.sep): continue
        
        output = open(filename,'wb')
        output.write(uncompressed)
        output.close()
    shutil.copytree(DWPath + os.sep + "dwpicker-" + latest_version + os.sep + "dwpicker" + os.sep, DWPath + os.sep + "dwpicker" + os.sep)
    shutil.rmtree(DWPath + os.sep + "dwpicker-" + latest_version + os.sep)

    zfobj.close()
    if os.path.isfile(tmpZipFile):     os.remove(tmpZipFile)

    import dwpicker
    try:
        from importlib import reload
    except:
        pass
    reload (dwpicker)
    dwpicker.show()`

PD: the version number on `text = '\n    New DreamWall Picker version "{0}" is available !    \n'`
Looks like this : 0, 6, 1
Perhaps it should look like: 0.6.1

**Comment by ndeebook** [comment]
Hello
Sorry but an update-checker is as far as we want to go.
We don't want to interfere with how studios manage their environments.
