### ISSUE TITLE
Tell me about the problem I encountered.

### ISSUE THREAD

**Issue by plateauRen** [DreamWall-Animation/dwpicker#4]
Hello, this picker is very excellent, but I will encounter some problems. I will list my questions here for your reference. 1. The view zoom setting is a little anti-human in Maya, and the main performance is whether it easy to be too large or too small; 2. Is it possible to add custom button shapes? 3. The picker will be reset every time it is opened. Can you remember where I put it and the window size? 4. Can the namespace settings be placed in a prominent position?

**Comment by plateauRen** [comment]
Thank you for your timely reply. 1. Please forgive me for not explaining my operation. I use a digital board to make animation, so my habit is to adjust the view in the middle of the alt + mouse, and the problem also happens here; 4. I think it can be similar to mgear and put it under the menu.
![7087B76A-586D-450E-AB0C-438529413A7C](https://user-images.githubusercontent.com/42939448/149558299-517766f2-5f35-4834-b17c-56f1153e058d.jpeg)

**Comment by luckylyk** [comment]
1.  My animators (using graphic tablet as well) asked me to be able to zoom with Alt + Middle mouse.
You want setting to adjust sensitivity or to select which button to use ?

4. Good idea. I can add this ASAP

**Comment by plateauRen** [comment]
Many of our animators are accustomed to using the tablet, and we also need to use alt+middle button to adjust the picker window. The problem I want to express is that using the tablet's alt+middle button to zoom the view is not accurate, and the view zoom will be very large. Finally  Wish you all the best

**Comment by plateauRen** [comment]
You're right, it should be a sensitivity issue, but I don't have a similar issue on mgear, so it shouldn't be a maya setting or hardware issue, I can try a few more times

**Comment by luckylyk** [comment]
Add a preference slider to adjust zoom sensitivity shouldn't be an issue. 
I will try to make zoom mouse button changeable as well. Keep an eye on this thread, i Will give you updates soon.

**Comment by plateauRen** [comment]
Please accept my heartfelt thanks.
由衷的表示我的感谢

**Comment by luckylyk** [comment]
Ok I'm not too reactive because i have a lot of work this week and your requests are more complexe than i though but it is coming very soon, probably tomorrow evening (UTC+1 timezone) :
Requests statuses
1. Done but will need your feedback about sensivity multiplier range required
2. Skipped
3. Done but do need more tests
4. Done, seems stable.

**Comment by plateauRen** [comment]
Thank you for your efforts, since I don't know how to get the specific zoom parameters, so I can only stupidly compare by video. The zooming feel of the maya window is what I think is appropriate, and the window zooming of dwpicker is what I mentioned. sensitiv

https://user-images.githubusercontent.com/42939448/149860526-4786f589-5f57-41ef-81f1-dec4ff12531f.mp4

e

**Comment by luckylyk** [comment]
Sorry, what i mean't was: As soon as I will publish changes, I will need your feedbacks" 
Which is the case now. The changes are not included in a proper release, but you can test them downloading latest source code.

I added a preference window
![image](https://user-images.githubusercontent.com/25019043/150027379-05766e55-7b97-4306-8f06-5f29d5de82f7.png)

The sensitivity multiplier is locked to a maximum. I can't really test if the value is accurate on my side. If minimum is still too sensitive, you can try to increase the value `MAX_SENSITIVITY = 200` in the python module: `dwpicker/preferences.py`.
If you have a better constant, tell me, i will report it in the code.

Sorry for the delay but you request was arch to implement :)

**Comment by luckylyk** [comment]
This is now published in release 0.1.0
