### ISSUE TITLE
Saving the picker after a change only saves the first opened one

### ISSUE THREAD

**Issue by Alehaaaa** [DreamWall-Animation/dwpicker#40]
### Whenever I have 2 pickers opened at once, the saving function will only affect the first one opened:

**1.** If I want to save the 2nd opened picker, I have to move the picker I want to save to the [first position](https://user-images.githubusercontent.com/105360073/168415835-353da8d3-c524-4b99-8621-feb5ec494025.png).
**2.** If I have two pickers opened and want to save them, only the first _will_ save.

**Comment by luckylyk** [comment]
Thanks for the accurate report.
I'll take a look asap

**Comment by luckylyk** [comment]
Solved :)
Change is included in the last commit.
I will release a new version asap.
Sorry for the delay.

Thanks again for the report
