### ISSUE TITLE
advance editor

### ISSUE THREAD

**Issue by Sidchou** [DreamWall-Animation/dwpicker#41]
some how the advance editor position of the image doesnt quite match the one in the window.
in advance editor position, ctrl + z undo multiple movement. 
when i move the image frame, i have to re-center the image by toggleing the fill

**Comment by luckylyk** [comment]
I'm not sure that I perfectly understand your issue.

To describe how it works: for some technical reasons, the picker view navigation is reset when you do a change in the editor. If your picker contains only one image, change his coordinates using advanced editor, view is fit to content, then nothing seems different. Actually, the coordinates are well changed.

I can investigate to break this automated camera change. But is it necessary, when you are editing the picker, I guess you are not really using the picker ?

Or you have another issue that I didn't get ?

**Comment by Sidchou** [comment]
so when i move the picture element, the element move, but the actual image in the element doesnt move until i toggle fill, then the image will recenter, and i know the editor and picker doesnt match because the image line up differently relative to the buttons position, it just a couple of pixel off vertically

**Comment by luckylyk** [comment]
Ok, ok, then I need more information as far as I struggle to reproduce that behavior.
I would like to know: 
 * What is the Maya version
 * Maya using Py2 or Py3
 * Picker version is well the latest one
 * What do you mean by: 'toggle fill'
 * Is there any feedback (errors) in the script moving the element ?

**Comment by Sidchou** [comment]
Maya Ver:2020
python ver: 2.7.11
pick version is the latest one
so the image will follow the element frame if i just drag it around, but if i type in the number, the frame in the editor will move, but the picture in editor and both picture and element in the picker doesnt move. turning on and off the "fit to shape" (toggle) fix the editor part, but does not fix the picker
if i type in the position it doesnt apply to the picker, it will show up on the editor, and when i undo they just all snap back to where they were

**Comment by luckylyk** [comment]
Ok, sorry for the misunderstanding, i got what you said: 
if the property: 'fit to shape' is false and you edit the item size by editing the value in the attribute editor, then the picture coordinate are not refreshed. It is just a display issue as the dat are good.
I can reproduce it now and i will fix that asap.

**Comment by luckylyk** [comment]
Ok bug fixed in the latest commit.
Some update trigger were missing at resize time.

Thanks for the report.
