### ISSUE TITLE
Request to encode picker data in base64

### ISSUE THREAD

**Issue by kalemas** [DreamWall-Animation/dwpicker#45]
Hi, we would like to request to change default picker data storage format from plain JSON to base64 encoded JSON.

1. because it is compact notation in maya scene 
2. our antivirus check raises when it encounter `python` keyword and removes picker data from scene.

I realize that you may not want to change that, but what if we make a patch to support storage plugins that would be passed to DwPicker constructor?

**Comment by luckylyk** [comment]
I have no strong opinion about this. I need to take a look to evaluate consequences about that move. I'm open for a change.

**Comment by kalemas** [comment]
No problem, maybe we will find a way to handle that keyword in antivirus. I just want to bring it up. Thank you for you openness and excellent picker!

i will think once again of do we really have to change default dwpicker storage behavior.

**Comment by luckylyk** [comment]
After taking a look. It think it doesn't implices too much problem.
As the picker seems already deployed and used in many studio (i'have no number, we don't track anything. But I got message in less than a day each time I introduce a new bug. So my policiy is to not disturb current production, I set those new behavior as optional (avoiding to break compatibility by the same way).
I will add this option Asap.

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/173917092-fc44d0a5-5d36-469b-8c74-c062230ea791.png)
Ok this is done :)

**Comment by kalemas** [comment]
It is very encouraging that how fast you implement features! Thank you.

> As the picker seems already deployed and used in many studio (i'have no number, we don't track anything. But I got message in less than a day each time I introduce a new bug. So my policiy is to not disturb current production, I set those new behavior as optional (avoiding to break compatibility by the same way).

it is quite a good policy, and i do not want to make something comfortable to me only but my intention is to have best ever open source solution. So i m open to discuss and research the best ways to do things in animation pickers, participate in development.

By the way did you encountered picker data size issues? If so i would advice to store compressed (zipped) data in base64.

**Comment by luckylyk** [comment]
we didn't encountered picker data size issue yet. We work with scene full of Smurfs and tons of controllers and pickers in the same time. I never benckmarked to check whats the limit actually.

**Comment by luckylyk** [comment]
Wouchaaa this is a huge topic !
I will start by: I'm probably too busy with our pipeline at the moment to implement something like this. Btw I'm open to review code, make some fixes and merge pull requestes :)

About your modifications:
1. The DwPicker development was driven by the AnimSchoolPicker's sudden licencing policy. Our goal was to make a tool close enough to not disturb animator habits switching tool in the middle of projects. Storing local data silently is what ASP does. It is using the "fileinfo" maya system to store data (in base64). I didn't used that, it complexifies the scene merging (import or reference). 
    - I kept data as JSON plain text, I was sure it would be usefull. After months of usage, I know today it is not.  
    - I used ScriptNode because make a custom node is excluded for that purpose to me. "Simple is better than complex" an I want to avoid unecessarily build environment, plugin requirement and data loss. I recently discovered that Maya provide a specific dummy node for those purpose: "mute". I will probably switch at some point.
    - In our workflow, the pickers are not included in the rigging. I never thaught it could be usefull to make this visible. Actually I'm more affraid about animators asking me: "Wtf is this ?".  The fonction gathering data from scene is not looking at the node type i think. I assume it could be easy to make it optionnal. My consern is: how do we manage multiple node data. Currently it merges them automatically. This need a clear design in case of change.

Way to ref the pickers:
1. This seems the easiest way as the "read-only" mode already exists on the Picker() object (aka `Picker.editable`). We would have to kind of item types in the `picker.json` that we can identify with a new key 'type':

    - `Local picker` (the current one), we can add a path as well for updates.
        e.g. `{'type': 'local', 'version': 0.5.1, 'shapes': [], 'general': { ... }}, 'source_path': '/home/....'`
    - `Referenced picker`
       e.g. `{'type': 'reference', 'path': '$PROD_ROOT/assets/character/nostromo/picker/picker.json}`
2. Less work for sure.
3. If tomorow Autodesk knock my door and ask an officiel implementation, that's the way I would use. Creating a custom node with array attributes holding all the pickers data is probably the best integration and would natively support reference edits. The cons are:
    - Plugin as to be load.
    - Pollute the scene with requirement.
    - What the format use to export the picker:
        - Maya scene: 
            - containing only the node ?
            - confusing for user.
            - bring with it probably a loft of nodes left behind.
            - risk of 'requirement' pollution.
        - Json:
            - Big difference between scene representation and exported data.
            - The exporter will a huge work.
    - Constant getAttr leads performance issue ? To evaluate.

**Comment by kalemas** [comment]
Agree that this is not important. Further more after blue pencil in 2023 - picker data will not be able to affect scene size significantly))
