### ISSUE TITLE
Namespace function  enhancement suggestion

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#46]
Hi,
  When the animation scene is more complex and there are many characters, there will be many namespaces and the namespace spelling is very similar. At this time, it will be troublesome to select or input in the list, and the appropriate namespace cannot be quickly matched. Is it possible to add a new  button, can get its namespace based on the currently selected controller, which will be very fast!

![xxx](https://user-images.githubusercontent.com/46336185/174531652-ebf03a49-ce48-49ba-8981-b6257f6b49a3.png)

**Comment by luckylyk** [comment]
Let's do it

**Comment by luckylyk** [comment]
here it is: Release 0.5.3 include the change.
It is also including the feature in the namespace selector menu bar
![image](https://user-images.githubusercontent.com/25019043/174783856-9d258aa7-67c2-48c9-ab77-c7cc3d267050.png)
![image](https://user-images.githubusercontent.com/25019043/174783933-01017fc0-9572-4be7-ab34-2226590108b2.png)

**Comment by Chuanzhen187** [comment]
great work
