### ISSUE TITLE
Picker Close icon suggestion

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#47]
Hi,
Can hide the closed icon and put it in the menu bar? When switching pickers, it is easy to click the close icon by mistake, and generally after opening a picker, closing a picker is also not a frequent operation

![xx](https://user-images.githubusercontent.com/46336185/174983485-3f0f97ff-234f-4ad5-9026-219a02978024.png)

**Comment by luckylyk** [comment]
Hi,
This close tab icon is a UI standard. I'm not up to change this for a non-standard behavior.
Btw, if you are afraid of sudden close, I'm ok to add an optional warning at each tab close event.
Tell me.

**Comment by Chuanzhen187** [comment]
yes,add a close event

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/175239365-d99f34ab-32e6-4b55-869d-a28634a96f20.png)
Done.
Have a nice day

**Comment by Chuanzhen187** [comment]
great work!
