### ISSUE TITLE
Improve namespace management

### ISSUE THREAD

**Issue by luckylyk** [DreamWall-Animation/dwpicker#49]
Support nested namespaces when it is partially set on the picker.

**Comment by thoolaeff** [comment]
on the topic of improved namespace management I would also like to tag on the function to have namespaces that are used in scripted buttons also be swapped out when a user changes the assigned namespace. animschool picker supported this if you put the namespaces inside ''. currently it seems that namespaces used in scripts are just hardcoded and not effected by the overal namespace assignment of the picker.

**Comment by luckylyk** [comment]
Finally allow the user customize the namepace switch at his ownway letting him set a custom function.
