### ISSUE TITLE
ISSUE, Button Right Click Action, script, not working maya 2022

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#5]
Hi there, I'm playing around with the picker, and i think came out great, i just wanted to post a few issues here as I'm finding them, as suggested by your readme.
(maya 2022)
When setting a button to use Right Click option, and setting it to HasCommand True, using Python, inputing a python command, wont work on the picker.
As i right click on the button, from the main UI view, nothing happens, and or no menu are showing for the inserted command.
Also noticed, that even tho i removed a selection Target (made the string Empty), by left clicking is still selecting the object that was removed from the Targets.

**Comment by SupZeta** [comment]
Im having the same problem. My FK/IK switch code isnt working with the picker. Same problem with left click code.
Nothing happens when clicking the button.

**Comment by luckylyk** [comment]
Indeed those button where not evaluated properly.
This should be fixed in latest commit (not included in release yet)

**Comment by SupZeta** [comment]
Picker stopped working for me with this fix.
I get this message now.

scripts\dwpicker\main.py line 20: cannot import name 'save_window_coordinates' from 'dwpicker.optionvar'

**Comment by luckylyk** [comment]
Sorry for this,
You are pobably very unlucky and downloaded the code right before the latest commit. This is issue as been fixed by commit 31 and stayed on the pitch for like 10 minutes :D.

**Comment by SupZeta** [comment]
Story of my life haha

**Comment by SupZeta** [comment]
Hi Lionel,

Im getting this message now.

> Code execution failed for shape: "IK/FK SWAP"
> name 'cmds' is not defined.

Could you check this please?

**Comment by luckylyk** [comment]
could send me the code you putted on the button and maybe the picker file (no need the maya scene associated) ?

**Comment by SupZeta** [comment]
Of course, appreciate the help.

[picker.zip](https://github.com/DreamWall-Animation/dwpicker/files/7908373/picker.zip)

**Comment by luckylyk** [comment]
Ok then it seems that the python 'exec' function fail at some point with long functions directly written in the picker.
The best short term solution is, instead of writing the entire function inside the picker, you should include it inside a module.py placed in the maya script folder. And then just import and execute.

Of course it doesn't release me from my duty to fix that :) But I don't know how much time it will take to spot the exact issue and fix it. You can follow this thread to keep you up: https://github.com/DreamWall-Animation/dwpicker/issues/13

**Comment by luckylyk** [comment]
@SupZeta and the issue#13 about your python code execute is solved :) !!
thanks to @ndeebook

**Comment by SupZeta** [comment]
Awesome! It works just fine now!
Thanks!
