### ISSUE TITLE
picker attributes copy and paste function

### ISSUE THREAD

**Issue by Chuanzhen187** [DreamWall-Animation/dwpicker#50]
in **advance editing window**,If we have the function of copying and pasting the color, size, border and other attributes of picker, it will be more convenient in the production process of picker.
Most pickers have the same **color, size, border** or other properties. The preset size of the **picker window** is invisible, and the effect can only be seen after creation. In the **advance editing window**, if we have this copy and paste instruction, we just need to adjust the size and color of one picker, and then copy it to other pickers.

**Comment by luckylyk** [comment]
I'm currently super busy,
but i will add a "Advanced copy" tool asap

**Comment by Chuanzhen187** [comment]
> I'm currently super busy, but i will add a "Advanced copy" tool asap

Thanks, picker will get better

**Comment by luckylyk** [comment]
Hey, sorry for the delay (vacations :))
Here it is: (release 0.6.0)
![image](https://user-images.githubusercontent.com/25019043/187170666-8648c7d0-f3d6-4a8c-96bb-dfa87d34227f.png)

**Comment by faxwang** [comment]
> Hey, sorry for the delay (vacations :)) Here it is: (release 0.6.0) ![image](https://user-images.githubusercontent.com/25019043/187170666-8648c7d0-f3d6-4a8c-96bb-dfa87d34227f.png)

how to use ,i not find how to open this window

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/189377433-0c83235a-4fa5-48fe-a2aa-93b81039321c.png)
Hi faxwang.
To copy attributes click the button 1.
to paste attributes click the button 2. The dialog should pops up and you will be able to select what attributes you want to transfert

**Comment by faxwang** [comment]
> ![image](https://user-images.githubusercontent.com/25019043/189377433-0c83235a-4fa5-48fe-a2aa-93b81039321c.png) Hi faxwang. To copy attributes click the button 1. to paste attributes click the button 2. The dialog should pops up and you will be able to select what attributes you want to transfer

# Traceback (most recent call last):
#   File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\designer\editor.py", line 156, in paste_settings
#     dialog = SettingsPaster()
#   File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\dialog.py", line 154, in __init__
#     enable_settings = cmds.optionVar(query=SETTINGS_TO_COPY).split(';')
# AttributeError: 'int' object has no attribute 'split'


thanks ,when is paste ,error in maya

**Comment by luckylyk** [comment]
seems you have a wrong settings save in you maya :/
could you try to run this in your python console and relaunch the picker ?

from maya import cmds
cmds.optionVar(remove='dwpicker_settings_to_copy')

**Comment by faxwang** [comment]
> seems you have a wrong settings save in you maya :/ could you try to run this in your python console and relaunch the picker ?
> 
> from maya import cmds cmds.optionVar(remove='dwpicker_settings_to_copy')

Traceback (most recent call last):
File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\dialog.py", line 211, in updated
save_optionvar(SETTINGS_TO_COPY, ';'.join(self.settings))
File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\dialog.py", line 206, in settings
self.groups[category].isChecked()]
KeyError: 'border'
Traceback (most recent call last):
File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\dialog.py", line 211, in updated
save_optionvar(SETTINGS_TO_COPY, ';'.join(self.settings))
File "C:/Users/98486/Documents/maya/2019/scripts\dwpicker\dialog.py", line 206, in settings
self.groups[category].isChecked()]
KeyError: 'border'
