### ISSUE TITLE
A few issues I've noticed after switching over to DreamWall picker from Animschool 

### ISSUE THREAD

**Issue by CSampson123** [DreamWall-Animation/dwpicker#51]
Hi firstly the picker is amazing and I have fully switched over from using Anim schools picker to yours with not much friction. 

I have found a couple issues that I'll list below, if any of these are my own fault and not that of the picker then please let me know

1 - 

When re opening maya scenes that previously had multiple different tabs open only the last opened tab will appear and all the other tabs will become that last opened tab. 

So If i have 3 pickers open in a maya scene - A, B, C and then close maya with A open. Once I  re open the maya scene DW picker will have 3 tabs in the picker but they will be A, A, A.  

This means any unsaved adjustments on pickers B + C that are scene specific only will be lost and I will need to reload pickers B + C and re-link them to my rigs in the scene. 

2 - 

Having a button that runs a custom script only works if the functions they are calling up are native to maya. If I am using other scripts that have their own functions I get this error - 

NameError: name 'X’ not defined

Even though if i type that function straight into mayas script editor It works instantly. So script buttons that were working in animschool picker no longer work in DW picker. 

3 - 

Holding down shift then selecting multiple controls works but holding down both Shift and Control and then selecting multiple controls dosen’t. This is a small one but since holding down both is the selection method in animschool picker it would be a nice quality of life to have it work in DW picker also. 

Thanks again for making such a useful tool. If you have any queries about the issues i’m running into let me know. Thanks

**Comment by luckylyk** [comment]
Hi,
All those thing sounds like old bug fixed from a while. Could you ensure you are using version 0.5.3  ?

**Comment by CSampson123** [comment]
Hey thanks for the speedy response. 

It seems like the new version fixes my first issue (#1 in previous post) so thanks for pointing that out.

I am still however having the two other issues.
#3 is pretty minor so thats not too much of a concern but I am currently still getting the error - 'NameError: name 'X’ not defined' (X being the function name of the scripts i'm trying to use) when I press a button with a script tied to it. This only happens when the script is not a default maya function. These bottons do however work in Animschool picker and straight in the script editor. Let me know if you know why this could be happening and if I'm doing something wrong. 

Thanks again :)

**Comment by luckylyk** [comment]
-2:
Define a function inside the script is supposed to work. I wonder if it is something specifique to your environment or something specific to your script. Could you provide a picker or a function which is typically failling ? Is it Python or Melscript ?
What is the Maya/Python version used ?

-3
Done. Keep in mind that ctrl+shit is still reserved for 'invert selection' action in advanded editor.
The update is not released yet, to get it, you can download the latest commit.

**Comment by CSampson123** [comment]
Thanks again for looking into this.

I've done some experimenting and I only seem to be having the issue with one specific script I am using. It is a toolset which includes an FK / IK switcher, reset pose button and some other useful things which I've previously been able to tie to buttons in aimschool picker. It is however an in house tool from a studio which I did not write so sadly I wont be able to share it for troubleshooting purposes. 

Thanks again for your help though. I love the picker :)

**Comment by luckylyk** [comment]
Oh I understand, but in this case, I can't do anything of help for a solution. 
I can only suggest you as workaround to put the scipt in a module. In the picker, just import and call the main function will do the trick.

I'm closing the ticket. Do not hesitate to re-open it or create a new one if situation evolve.

Good luck
Lio
