### ISSUE TITLE
V0.6.1 will not open 

### ISSUE THREAD

**Issue by CSampson123** [DreamWall-Animation/dwpicker#55]
Hi I am getting the error when trying to open the newest verison V0.6.1

 # Error: ImportError: file 
C:/Users/(name)/Documents/maya/scripts\dwpicker\updatechecker.py line 3: No module named request

I got someone else to test this and they're also getting this error. Could this be an issue with the newest version? 

Thanks again for the continued updates :)

**Comment by ndeebook** [comment]
Hello,
I just fixed it in the latest commit (was only working with Maya versions using python 3).
