### ISSUE TITLE
Relative path for images

### ISSUE THREAD

**Issue by AtomicPic** [DreamWall-Animation/dwpicker#57]
Is it possible to set relative path to images? 
For example, i would like to have a folder named "pickers" inside my Maya project's folder and simply set: "./pickers/mypicker.png"  
From there, i should be able to use my pickers from differents working station without having to set every time my path for the image.
Thank's in advance!

**Comment by luckylyk** [comment]
Hi !
Unfortunately this is not possible. The reason is the picker data are fully imported and contained by mayascene itself. Then it is not possible to guess what's the root off relative path. Rely on maya scene path cannot work either, that would force you to place all youre scene in the same folder.
For pipeline purpose, the picker support environment variable paths.
If you set a path in you environment, you can set images like this: "$PICKER_IMAGES_PATH/my_image.png"

**Comment by AtomicPic** [comment]
Wow that was fast! 
Thank you so much! I will add this variable in my Maya.env

**Comment by AtomicPic** [comment]
Unfortunately, i can't make it work.

![image](https://user-images.githubusercontent.com/114571138/192748661-a7ae272d-5e46-4601-9ae3-c4cb0ad53798.png)

My variable is set and available, but i m not sure how to make it readable the "$PICKER_IMAGES_PATH".

string $pickerImagesPath = `getenv "PICKER_IMAGES_PATH"`; 
print($pickerImagesPath+"\n");

Those lines give me the right path to my folder. 

Maybe somehow put (`getenv "PICKER_IMAGES_PATH"`)+"/test.png" in the textinput of the image path?

**Comment by luckylyk** [comment]
It has to be used like this
![image](https://user-images.githubusercontent.com/25019043/192751712-aa6e395b-c3d7-4a3c-bf55-e0226728a9df.png)

I guess your path is not good ?
you can try those python lines to ensure the image path is found:
`import os
print(os.path.exists(os.path.expandvars('$PICKER_IMAGES_PATH/test.png')))`

**Comment by AtomicPic** [comment]
Thanks for your help!

The python lines return "True" so i guess the path is valid. 

I still don't understand why $PICKER_IMAGES_PATH is interpret as a strict string and not as a variable containing the path.

**Comment by luckylyk** [comment]
may you can try with bracket ?
{$PICKER_IMAGES_PATH}/test.png

**Comment by luckylyk** [comment]
I suddenly realised the dialog in your screenshot is not part of the actual picker. Support for environment variable has been added with version 0.5.0 20 May 2022. 
Could you check you are up-to-date ?

**Comment by AtomicPic** [comment]
Yeah! That was it! Sorry, it's on me. I should have begin by cheking if i was up to date! Thank's again for your help and your amazing tool!
