### ISSUE TITLE
Ability to display a submenu list of buttons(like hotbox designer)

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#58]
Hello,
i noticed that on your hotbox_designer, there is a possibility to display a subMenu clicking a button (via script), and i would like to do the same but using the picker buttons.

Basically, i want to make certain buttons to be picker functions buttons, and these would "open" a sub-menu (these could also be other json file pickers like on the hotbox_designer), either running this as a right click action for a button or a left click.

This would have to be displayed on top or as part of the main UI or perhaps only display as a layout widget with the buttons (no ui boarder)?

Do you know if this is already possible?

**Comment by alfsici** [comment]
ok, i think i might actually have resolved it using this : 
I used your "independent picker view example" and grabbed the widget pointer as my popUp ui parent window:

`        view = PickerView_popUp(editable=False, parent=uiWin)
        view.register_callbacks()
        view.setWindowFlags(QtCore.Qt.Tool)
        #This window flag QtCore.Qt.Popup is the Key to make the popUp widget to work without the frame visible
        view.setWindowFlags(QtCore.Qt.Popup)
        view.set_shapes(shapes)
        view.setFixedSize(win_size[0],win_size[1])  # i am grabbing these from the saved json picker file
        view.move(QtGui.QCursor.pos())   # i move the widget under the current cursor position
        view.show() # show the widget
        view.reset()  # reset its zoom (somehow if i don't reset it, it breaks visually)
`

**Comment by luckylyk** [comment]
Hi Alfo,
Yes this seems the good way to do for the moment.
I can add that option to the system.
I Add this to my todo list

**Comment by alfsici** [comment]
sounds good, and thank you.
Ideally, the popUp would not have any zoom nor move capabilities, so to keep the menu visually solid and with the correct dimensions that are set when making/editing the ui.


I am also toying around with the idea of making a sliderWidget as well as a check.
eg: 
User right clicks a button on the main picker ui, a list of sliders type widget popsUp, this can go left to right or up down(depending how they have been designed), when the slider moves, the script function is run (imagine a keySmooth operation or a inbetweener type of thing)

any thoughts on this ?

**Comment by luckylyk** [comment]
To lock the PickerView, a Property already existe
view = PickerView(...)
view.zoom_locked = True

I already though about create slider and bidimensionnal slider. It is tottally feasable and not so hard to but. But it requires to an entire new class of shape and need to writr another attribute editor for that. + A callback system to Drive values. This is a lot of work to make something hard to use for non technical artist. I'm open to the Idea but i clearly dont have time to Dev this features.

**Comment by luckylyk** [comment]
Disable right Click menu on the PickerView is fairly simple too
view = PickerView() 
view.editable = False

**Comment by alfsici** [comment]
One thing to note, to get the "full size" of the widget, i had to also modify the reset() function, inside PickerView() class, so that the 
rect size would be calculated with 0 extra space around it, this way, when the right click widget popsUp, it shows correctly.
(in my case i created an entire new class for this by coping pickerView , although not sure what would the best solution for this, since the tool is already complex as is)

The user then, can create custom popUps(the usual way) and when are displayed, they will be matching the size they specify in the main UI editor.

rect = QtCore.QRect(0, 0 , self.size().width(), self.size().height())

**Comment by luckylyk** [comment]
I guess we can add an argument to the reset to disable extra space

**Comment by luckylyk** [comment]
Finally (2 years later ^^) I just implemented a way to customize the picker context menu per shape :)

![image](https://github.com/user-attachments/assets/32cb4558-2b29-4e93-b6b0-31d216f1b03a)
