### ISSUE TITLE
Box selection cannot be selected to the button

### ISSUE THREAD

**Issue by faxwang** [DreamWall-Animation/dwpicker#60]
maya:2019,picker version:0.6.3
Box selection cannot be selected to the button, only click to select.
show in gif
![选择](https://user-images.githubusercontent.com/39043550/213402831-8adb9741-a520-4bf0-b048-61b0690710c2.gif)

**Comment by luckylyk** [comment]
Very odd bug .. Seems fixed in next release. I'll keep you up asap

**Comment by luckylyk** [comment]
Should be fixed with 0.6.4
