### ISSUE TITLE
Undo/Redo amélioration

### ISSUE THREAD

**Issue by Raho432** [DreamWall-Animation/dwpicker#61]
Lors de l'exécution d'un custom script, par exemple un reset ctr, il faut faire autant de undo qu'il y a d'objets sélectionnés pour revenir à l'état d'avant appuie sur le bouton qui exécute la commande.
Il serait super qu'avec un seul ctr Z, il restaure l'état des tous les objets sélectionnés.

Merci beaucoup, votre tool est super.

**Comment by luckylyk** [comment]
Salut,
C'est probablement ta commandes qui créé plusieurs undo. J'hésite du coup a forcer la combinaison des undos car c'est le comportement standard de maya.
En revanche, tu peux peux encadrer ta commande avec :

cmds.undoInfo(openChunk=True)
... ta fonction
cmds.undoInfo(closeChunk=True)

Faut que je dorme sur l'idée, voir si je le force.

**Comment by Raho432** [comment]
Quand j'exécute ma commande via le script editor, je n'ai pas ce comportement par contre.
Merci beaucoup pour le tip:⁠-⁠)

**Comment by luckylyk** [comment]
Ceci est finalement disponnible nativement depuis la release 0.11.0 via le createur de commands (dans l'attributes editor de l'advanced editor)
![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/64ee90b6-7442-43a8-be3e-10207c3c79e5)
