### ISSUE TITLE
The order of selection of objects

### ISSUE THREAD

**Issue by Sprite37529** [DreamWall-Animation/dwpicker#62]
Hi. This is a very good tool.

Problem:
I have saved several objects in the button targets. Saved them in a certain order: obj1, obj2, obj3. After clicking on the button, the objects are selected in a different order: obj2, obj3, obj1. This can be seen in the graph editor.

In the targets text string, the names of objects are sorted alphabetically. Objects are selected sometimes in reverse order, and sometimes randomly.

https://user-images.githubusercontent.com/127329183/223775195-e3639e0c-d68a-4386-b5f4-5b5203cc1f36.mp4

It will be very good if the objects are written to the target text string and selected in the order in which they were originally selected.

Thank you if you decide to solve this problem and release a new release.

**Comment by luckylyk** [comment]
Hi Sprite,
Sorry for the ridiculously long delay for a so basic fix !
This should be improved in version 0.6.5

Regards !

**Comment by Sprite37529** [comment]
Hi Lionel. Thank you very much. This is a super picker)

чт, 8 июн. 2023 г. в 15:15, Lionel Brouyère ***@***.***>:
