### ISSUE TITLE
dwpicker not working with maya 2024 (RESOLVED)

### ISSUE THREAD

**Issue by mikesimo10** [DreamWall-Animation/dwpicker#63]
using the same install method for maya 2023 and below, I get a syntax error everytime I try to add the dwpicker script into maya

**Comment by luckylyk** [comment]
sorry for the delay,
It seems that it works on our side and impossible to reproduce the issue. Could you provide the entire stack strace (visible in the maya's script editor) for more detail ?

**Comment by luckylyk** [comment]
Cool !
Good luck

**Comment by JRFK3D** [comment]
If anyone still having the problem, I'm worked for me just pasting the folder called dwpicker into the path, only  that folder and its content, not into another folder.
