### ISSUE TITLE
Picker not working when referenced

### ISSUE THREAD

**Issue by OllyRoy** [DreamWall-Animation/dwpicker#64]
Hello! first of all I love this plugin great work. 
I'm having an issue when I reference my file. The buttons that select all controls or multiple at once stop working and give me an error saying "Some nodes exist more than once:"
Is there a way around this besides deleting the buttons that select multiple controls?

They all work as they should in the rig file it's just when I reference.

**Comment by luckylyk** [comment]
Uy

**Comment by luckylyk** [comment]
Hi, sorry for the delay :)
This means that multiple nodes have the same name in your scene unfortunately. The picker does not support name clash :/
