### ISSUE TITLE
quickly set namespace

### ISSUE THREAD

**Issue by UCHIHAHA103** [DreamWall-Animation/dwpicker#68]
May I ask, what is the Python command for this button? I want to set it as a shortcut, so when there are many characters in the scene, I can quickly set this character as the namespace.
![image](https://github.com/DreamWall-Animation/dwpicker/assets/61904674/b2a02a20-c19f-418a-9f48-5a61af318a58)

**Comment by UCHIHAHA103** [comment]
Additionally, I have an idea for a more convenient way to select namespaces. Here, a toggle button is needed. When turned on, it will automatically get the currently selected character as the namespace. My idea is to insert a line in the select_targets command to get the current namespace. But I'm a beginner and I'm not sure how to proceed.

Expected implementation: The current controlled character is A, when I select any controller of character B, the picker will automatically change the namespace to B. This way, I don't have to manually select the namespace.

![image](https://github.com/DreamWall-Animation/dwpicker/assets/61904674/7058de37-3e29-4e05-87f6-4a87d1eae947)

![image](https://github.com/DreamWall-Animation/dwpicker/assets/61904674/e52819f7-ae64-4864-aa4b-5dc1b0d55ba7)
Looking forward to your reply！

**Comment by luckylyk** [comment]
Hi!
 i'm on the road for vacation. Si it is hard to reply accurately. For the command i cant tell you the without checking the code on my computer (which is not coming with me) 😁.

For the namespace switch, as far as i remember, on the preferences, you can activate a "auto switch tab from selection" behavior.
This is a callback which detect at selection change time what is the current délecter namespace. If it correspond to a picker opened, it switch the tab.

In youre case, i assume you get multiple time the same rig referenced in youre scene. The best strategy is to open multiple time the same picker and setup a different namespace for each.
With auto switch, you should a kind of behavior you describe

**Comment by UCHIHAHA103** [comment]
Our project requires each role to use the same tabs for easy maintenance. The behavior of this switch should be that before every select_targets, the button to retrieve the current application name should be clicked first.
I will also try to see if each role can use different tabs.
Wishing you a pleasant vacation！

![image](https://github.com/DreamWall-Animation/dwpicker/assets/61904674/6b562974-2004-4363-8682-7e606cb0cdc1)

**Comment by luckylyk** [comment]
Sorry for the delay, i toke a bit of time to implement this:
![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/e6cd9f85-0dbc-4480-9b43-3119ae9eb2ab)

Checking that preferences should solve your issue
This is not available in a proper release, But you will get it by downloading the latest commit.
Have a nice week.
Lionel
