### ISSUE TITLE
Custom shape Buttons

### ISSUE THREAD

**Issue by dpristay** [DreamWall-Animation/dwpicker#69]
Hi. How can i add custom shape buttons. Maybe SVG?

**Comment by luckylyk** [comment]
Hi,
This is not supported. The only way to fake this is to make a png with transparency and set the button border and background transparent.

**Comment by dpristay** [comment]
I tried this method. But the problem is if you click on transparent area button is working.

**Comment by luckylyk** [comment]
Yep, that's the limite. Same with round shape. Unfortunatelly all is based on squares. But as it complexify a lot of things and requises a lot of development, this is not currently planned

**Comment by dpristay** [comment]
Ok. Thank you)
