### ISSUE TITLE
Ability to lock the editing of a picker

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#7]
It would be great to be able to Lock the editing of a picker , for instance, you wouldn't want to have a team accidentally override a ui, what i would imagine, is that a team would use a command to run the "viewer" or the "editor".
The viewer is merely the main UI (file load), with no other options to edit any of the buttons.

something like this : 
Editor : 
import dwpicker
dwpicker.show(edit=True)

And for the viewer :
import dwpicker
dwpicker.show(editor=False, "paths to picker A", "path to picker B", "path to picker C", "etc")

This way, an entire team will be able to open pre made pickers, without accidentally override them.

**Comment by luckylyk** [comment]
I Buy this too

**Comment by luckylyk** [comment]
Hi, this is now implemented in the latest commit !

```
pickers = [ "paths to picker A", "path to picker B", "path to picker C"]
dwpicker.show(editable=False, pickers=pickers, ignore_scene_pickers=True)
```
editable: bool, if false it is not possible to edit the opened pickers
pickers: pre open some pickers
ignore_scene_pickers: if the scene contains picker data, this will ignore them but preserve the data of edition.

Sorry for the delay, as this was a request, it is not prio but i'm trying to keep going and do not forget them :).

**Comment by alfsici** [comment]
You are awesome, thank you for the update.
