### ISSUE TITLE
Maya hotkey interrupted when DWPicker is docked

### ISSUE THREAD

**Issue by shubham-12348** [DreamWall-Animation/dwpicker#71]
I have hotkey 'ALT + E' to toggle graph editor in maya which works fine until the DWPicker is not docked. As soon as I dock it, 'ALT + E' selects the edit menu under DWPicker.

**Comment by luckylyk** [comment]
Hi
Can you specify the OS and the Maya version you are using ? This is typically linked to the OS window managment behavior I can't reproduce on my current environment to analyse how to improve this.

**Comment by luckylyk** [comment]
Hi whitout any feedbacks I consider this ticket closed. Do not hesitate to reopen it if you have more information for me.

**Comment by shubham-12348** [comment]
Hey!
Sorry. I missed out this somehow. I'm using windows 10 pro and maya 23.

**Comment by shubham-12348** [comment]
Also, im using following script to toggle graph editor -

if (`window -q -ex graphEditor1Window`)
	deleteUI graphEditor1Window;

else

	tearOffPanel "Graph Editor" "graphEditor" true;
