### ISSUE TITLE
Groups and visibility switch

### ISSUE THREAD

**Issue by orofri** [DreamWall-Animation/dwpicker#75]
Hey,

It would be nice to be able to group few buttons together and create a visibility switch to hide/show that group of buttons on the picker.
It's very useful for micro ctrls of eyelids and mouth, those are usually needed only on polish stage.

Thanks!

**Comment by luckylyk** [comment]
Ok this is a great idea, but lot of work.
So wont be for tomorrow, but keep the ticket open for the moment I get some time to implement.

**Comment by luckylyk** [comment]
This is feature is now availbable with release 0.10.0 !
