### ISSUE TITLE
Ctrl+q hotkey closes the tool

### ISSUE THREAD

**Issue by duhreetoh** [DreamWall-Animation/dwpicker#76]
Great tool! One thing keeping me from using it, though.

Ctrl+q is one of my most used hotkeys for animation purposes

This hotkey, frustratingly, closes the tool. No combination of focus behavior makes this workable for me

Is a hotkey for closing the tool really necessary? And if so, how about not on the left side quadrant of the keyboard where commonly used hotkeys (for operations done over and over) are most often used?

Great stuff otherwise, thank you

**Comment by luckylyk** [comment]
Said like this, I guess you are right on the fact it is totally overkill to have this hotkey for the picker. 
By the way, this is the standard shortcut to quit maya in qwerty and qwerty keyboard. Did you remapped your shortcuts ? No sure to know why you use it.

Of course I can't remove before asking around me if anyone is relying on it, and I'm very busy with pipeline at the moment. I'll keep the ticket open until I solve that.

If by the time I solve that, you really need to get rid of it, you can just remove the line 89 of the main.py in the dwpicker folder:
![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/7f017e84-4947-4f94-a5f8-a5ef1a5004ba)


cheers !

**Comment by luckylyk** [comment]
Hey !
I needed a bit of time to implement something well, But the Release 0.9.0 include a HotKey editor, allow you to edit or disable the shortcut you dont want to have !! (Only for you !)

![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/9bb5b553-85a9-4b2f-b49f-350b5530147b)

Have a nice Week-end !
Lio
