### ISSUE TITLE
Getting OPENSSL: FATAL error on Maya 2023

### ISSUE THREAD

**Issue by jtrner** [DreamWall-Animation/dwpicker#80]
First time I'm using this amazing dwpicker on my PC but I'm getting this error on Maya 2023
https://i.imgur.com/5ErfEdt.png

I tested on my laptop that has both Maya 2022 and Maya 2023 as well, and dwpicker is running fine on both Maya versions.

So its most probably an issue on my computer. However I'm not quite sure if its a plugin problem or a driver issue.

I already tried to disable ALL the plugins and disable autoload too but I'm still getting the fatal error.

Btw, this error is causing Maya to crash.

Anyone have any idea where to look at?
Appreciate any help

OS: Windows 10 Enterprise (PC and Laptop)
Maya 2023.3 (PC and Laptop)

**Comment by jtrner** [comment]
Quick update:

Has been resolved by Lionel using below script:

`import dwpicker
from dwpicker.optionvar import save_optionvar
save_optionvar('dwpicker_check_for_update', 0)
dwpicker.show()`

Thank you

**Comment by luckylyk** [comment]
Hi, I disabled this features by default now on Maya2023
By the way, If someone still encounter this crash, it can happen if he imported prefs from older maya or already launcher picker from old version.
In that case running those line will fix the issue !

Thank for the report.
Cheers 
Lio

```python
from dwpicker.optionvar import save_optionvar
save_optionvar('dwpicker_check_for_update', 0)
