### ISSUE TITLE
Downlaoding Issue

### ISSUE THREAD

**Issue by MarcWH** [DreamWall-Animation/dwpicker#82]
Hello!

I'm currently having an issue while downloading the picker. When I run the script command:

 "import dwpicker
dwpicker.show()"

 to activate the picker it gives me an error: 

"# Error: AttributeError: file <maya console> line 2: module 'dwpicker' has no attribute 'show'"

I took the folder from the zip file called "dwpicker" and put it into the maya scripts folder as the instruction said to do. I'm attaching a screenshot to show what I see on maya.

 I'm not sure what I'm doing wrong, would appreciate if someone could help me!

![Screenshot 2024-04-02 at 12 43 20 PM](https://github.com/DreamWall-Animation/dwpicker/assets/165822675/d866a3f2-1e83-46e9-a72d-22893703a9fb)

Thanks!

**Comment by luckylyk** [comment]
Hi Mark
Can you specify Maya's version, OS and provide a screenshot of your explorer folder with dwpicker folder ? (to ensure you copy the right one)

**Comment by Panda8341** [comment]
HI @luckylyk   import dwpicker
dwpicker.show()
# Error: AttributeError: file <maya console> line 2: 'module' object has no attribute 'show' #  I got this problem while installing in maya 2020 i copied dwpicker and pasted it in maya scripts and i open maya and run script using this import dwpicker
dwpicker.show() then i got this problem how can i solve it
