### ISSUE TITLE
Hotkey to Change Tab Forward and Back

### ISSUE THREAD

**Issue by johnturello** [DreamWall-Animation/dwpicker#83]
Is it possible to get a command and hotkey to change the current tab to the next or previous one?

**Comment by luckylyk** [comment]
![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/7d060a31-e114-4683-9c84-ba6558d9dde3)
Ala, not available in Release yet, but you already can download last commit.

Cheers
Lio
