### ISSUE TITLE
suggestion: nested namespace

### ISSUE THREAD

**Issue by bafly** [DreamWall-Animation/dwpicker#84]
you can use temporarily disable any namespace level with Namespace Editor:
 - set current namespace to desired one
 - tick option - `relative namespace` in Options menu
 - do your stuff
 - roll back current namespace :root 
 - untick `relative namespace`

**Comment by luckylyk** [comment]
Never too late to reply sorry ^^
Finally, as each studio has is own naming conventions rule and to avoid to make the vanilla behavior too complexe, I decided to open the "replace namespace" behavior. The command dwpicker.show has now an argument to let user write his own function.

Have a nice (8 month later) december ^^

**Comment by bafly** [comment]
thank you!
