### ISSUE TITLE
Visibility feature issue

### ISSUE THREAD

**Issue by Rohit624** [DreamWall-Animation/dwpicker#87]
I prefer to drag select multiple ctrls in one go. If there are some invisible ctrls in the selection box area then picker selects them too. It would be better if selection only selects the visible buttons.

**Comment by luckylyk** [comment]
Hi ! Thanks for the report and clear description. We encounter a huge flow of emergency right now, but I will fix it as soon as possible.

**Comment by luckylyk** [comment]
Fix !
