### ISSUE TITLE
Error: AttributeError: file <maya console> line 2: 'module' object has no attribute 'show'

### ISSUE THREAD

**Issue by LastDaySeptember** [DreamWall-Animation/dwpicker#89]
During installation, in Python editor there is an error.
Python script is copied from the installation guide (import dwpicker...)

**Error:** AttributeError: file <maya console> line 2: 'module' object has no attribute 'show'

**Comment by luckylyk** [comment]
Hi, could you please detail how/where you did copied the dwpicker folder ?

**Comment by LastDaySeptember** [comment]
Hi, I have tried the older version and it seems to install (havenůt tried
it yet). Before I have tried versions 2024 and then 0.9.1, but the version
0.6.0 worked for me. I am working with Maya 2020, cause i have some older
plugins, so i dont want yet to switch to newer versions. I guess Python 2.7
is old :D
Thank you for your work!
A

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Neobsahuje
žádné viry.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
