### ISSUE TITLE
Advanced Option should have Save/PickerTitle/Picker namespace buttons

### ISSUE THREAD

**Issue by alfsici** [DreamWall-Animation/dwpicker#9]
Advanced Option Editor, should have 
the Save and save As buttons,
should have a PickerTitle visible that is easy to change and see , and should also display and be able to change the Picker namespace , to keep everything a bit more organized .

**Comment by luckylyk** [comment]
I Buy this one

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/158625423-2c8f1a8e-493d-44f3-bd27-5fb83d5c68a3.png)
Rename title and lock zoom and navigation are now available in the Advanced Editor.
Add Save/Save As and Namespace seems to add too much complexification for now and is delayed for later.
