### ISSUE TITLE
Create buttons and forms from Nurbs Curves or other shapes apart rectangles and circles.

### ISSUE THREAD

**Issue by Wassea92** [DreamWall-Animation/dwpicker#91]
Hi @luckylyk ,
I thought maybe it would be very nice to have the ability to create new button shapes from a nurbs curve or to drag lines with pencil into the advanced editing window? Or transform a nurb curve from viewport into a button in picker?

**Comment by kalemas** [comment]
I m also thinking of custom shapes. Maybe integrating svg would be easy easiest approach, maybe there are lightweight svg editors that we would embed, so shape would be edited right in dwPicker. And svg would be embedded in json file, so there would be 

```json
"shape_registry": {
    "cross": "<svg fill="#000000" height="200px" width="200px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-39.2 -39.2 568.40 568.40" xml:space="preserve" stroke="#000000" stroke-width="49"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="5.88"></g><g id="SVGRepo_iconCarrier"> <polygon points="222.031,490 267.969,490 267.969,267.969 490,267.969 490,222.031 267.969,222.031 267.969,0 222.031,0 222.031,222.031 0,222.031 0,267.969 222.031,267.969 "></polygon> </g></svg>"
}
```

those would be selected in shape type drop down.

**Comment by luckylyk** [comment]
The thing is the collision procession optimisation for custom shapes could be a drop down. And it is a large dev to write a tool able to draw shapes. I'm not super up and motivated to implement that. Right now, the picker is only managing rect to rect detection. I ofter see pickers with millions of buttons shared by people.

However i'm ok to make a render system allowing user to create a png from a maya curve, to easily reproduce the controller look in the picker. But it still going to be square image that you need to save somewhere.

**Comment by Wassea92** [comment]
Is there an alternative way ( not too heavy for the picker ) to have button shapes and lines other than using squares and circles?

**Comment by luckylyk** [comment]
@Wassea92 @kalemas 
What about something like this ? :) Still in progress, ergonomy is what it is and it is not an adobe canvas, but quite permissive :)
Regards to QT documentation, those shape collisions are between 10 and 300 time slower to compute, but I guess it is ok to have 50 shapes li,e this in the picker
https://github.com/user-attachments/assets/e1eda29f-8b37-482e-a0c6-e0f6447f005f

**Comment by kalemas** [comment]
@luckylyk it looks wonderful! But still animators will demand yet more)

**Comment by Wassea92** [comment]
Wow, guys @kalemas , @luckylyk , you did an amazing job! I didn't expect such a detailed tool implementation. I thought maybe adding  more shapes in picker like triangle, line, or hexagon would be enough, but you took it to the next level. Respect and love to you all. Thanks!
