### ISSUE TITLE
invisible buttons prevent selection

### ISSUE THREAD

**Issue by Zellstoff** [DreamWall-Animation/dwpicker#94]
Hi!
I have buttons set up like this.
![Screenshot 2024-06-28 131604](https://github.com/DreamWall-Animation/dwpicker/assets/15332222/2c497b81-464c-4b53-a67d-dc59fe3e217e)
The gray boxes in the middle are on a visibility layer. If visibility is off it still will not let me select in the spots where the gray box would be.

**Comment by luckylyk** [comment]
Hi Zellstoff,
this is supposed to be fixed with the 0.11.2 released on june 7th.
Could you confirm that you are not working on older version ?

Thanks
Lio

**Comment by Zellstoff** [comment]
Hi Lio,

I'm working with version 0.11.2

**Comment by luckylyk** [comment]
Sorry for long delay (summer time ^^)
taking a look asap

**Comment by luckylyk** [comment]
this is fixed in last commit,
Will be officially included in 0.11.3 !
