### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by saleemian** [DreamWall-Animation/dwpicker#95]
I did this script according to your instruction, but no matter what I do, the script does not run, it gives an error
It gives this error
import dwpicker
dwpicker.show()
# Error: ImportError: file <maya console> line 1: No module named dwpicker #
I am working in Maya 2020 and I copied this script, please help me

**Comment by mainnguyen63** [comment]
I'm working Maya 2020 too. I have another error after running the same code in Maya: 
import dwpicker
dwpicker.show()

# Error: AttributeError: file <maya console> line 2: 'module' object has no attribute 'show' #

**Comment by mainnguyen63** [comment]
I download maya 2024, install dreamwall picker like in ready me. All the same steps I did in maya 2020. In maya2024, dreamwall pickers are installed without any hiccups. 
I still didn't know what was the problem, I would like to use the picker in maya2020 because of my animbot version

**Comment by mainnguyen63** [comment]
> I did this script according to your instruction, but no matter what I do, the script does not run, it gives an error It gives this error import dwpicker dwpicker.show()
> 
> # Error: ImportError: file line 1: No module named dwpicker
> I am working in Maya 2020 and I copied this script, please help me

The lastest version of DreamWall Picker doesn't work in maya 2020. Up til Release 0.11.1, it works with maya 2020

**Comment by DJLegends1011** [comment]
so anybody know how to fix this on maya 2025?

**Comment by WangYihupou** [comment]
I'm working Maya 2020 too. I have another error after running the same code in Maya:

# Error: AttributeError: file <maya console> line 2: module 'dwpicker' has no attribute 'show'

**Comment by brunet1990** [comment]
> so anybody know how to fix this on maya 2025?
you probably copy dwpicker-main folder, but you need to copy folder inside this folder with name dwpicker (without any main and so on). once you do that you will be fine.

**Comment by brunet1990** [comment]
> I'm working Maya 2020 too. I have another error after running the same code in Maya:
> 
> # Error: AttributeError: file line 2: module 'dwpicker' has no attribute 'show'

> so anybody know how to fix this on maya 2025?
you probably copy dwpicker-main folder, but you need to copy folder inside this folder with name dwpicker (without any main and so on). once you do that you will be fine.

**Comment by fabiencollet** [comment]
Hello,
I found the error it was due to the f string in the `__init__.py` file at the line 9
I will do a Pull request to propose the fix

**Comment by fabiencollet** [comment]
here is the Pull request:
https://github.com/DreamWall-Animation/dwpicker/pull/100

**Comment by miksand** [comment]
Also just installed this version on Maya 2020.
can not load in the Picker Window.
Version 0.11.1 still works on Maya 2020.

Got error: 
# Error: SyntaxError: file <maya console> line 1: invalid syntax
and
# Error: AttributeError: file <maya console> line 2: 'module' object has no attribute 'show'

**Comment by fabiencollet** [comment]
@miksand @brunet1990 @WangYihupou @mainnguyen63 @saleemian 
You could fix the plugin by yourself before the merging of the fix propose here : https://github.com/DreamWall-Animation/dwpicker/pull/100

### Step to fix it manually:
- Open the File `__init__.py` located in the main folder `dwpicker`
- Replace the ligne 9 of the script (this one bellow) :
` sys.path.append(f'{os.path.dirname(__file__)}/qt_remapping')`
- With this code :
`sys.path.append('{}/qt_remapping'.format(os.path.dirname(__file__)))`
- Save the file and quit
- Relaunch `Maya-2020`, launch the script and it will work

let me know if you get trouble to fix it

**Comment by miksand** [comment]
Thank you. The fix works!

**Comment by mainnguyen63** [comment]
@fabiencollet The fix works, thank you!!

**Comment by luckylyk** [comment]
How god sorry, I was off for a while.
Hoorray for fabien
Sorry pple for that

**Comment by luckylyk** [comment]
> here is the Pull request: #100

This is now part of official version !
Thanks Fabien
