### ISSUE TITLE
Picker editor issue

### ISSUE THREAD

**Issue by JacobProvencher** [DreamWall-Animation/dwpicker#96]
Hello guys! Whenever I try to edit my picker with the advanced editing picker, nothing shows up, even if there is already a button in the "normal" editor. Am I missing something? I double checked if my installation was done correctly : put the dwpicker folder in .../documents/maya/scripts folder. But still having the same issue.
![Capture d’écran 2024-07-09 095814](https://github.com/DreamWall-Animation/dwpicker/assets/159086368/de7d9fbf-d778-4902-b037-a821151a8eec)

**Comment by luckylyk** [comment]
Hi !
This is due to a dumb coordinate system which much change a some point.
Your items are out of canvas. Just click this to reframe them.
![image](https://github.com/DreamWall-Animation/dwpicker/assets/25019043/34ab2e21-8943-4081-84d5-e4e705680ac5)
