### ISSUE TITLE
Removed namespace functions on picker.py at release 0.5.3

### ISSUE THREAD

**Issue by soseki90** [DreamWall-Animation/dwpicker#99]
Since version 0.5.3 the “_namespace” and “detect_picker_namespace” functions were removed from picker.py. They were very useful when adding scripts in buttons that only affect the asset with the namespace set in the picker.

I have not found an alternative in case the removal of these two functions had been intentional and replaced by another methodology. Even one of the scripts in the “scripts” folder that comes with the download uses these functions.

Thank you very much for this wonderful picker.

**Comment by soseki90** [comment]
Oops, I just saw that you distributed the code and now those functions are in namespace.py, so just warning that the “detect_current_namespace.py” script is not updated with this change.

**Comment by luckylyk** [comment]
:)
